#!/usr/bin/env python3

#       Class Desciption
# Author: Diaeddin Rimawi
# Email: dmrimawi@gmail.com + drimawi@unibz.it
# This is a custom Exception fot exceptions generated by CUDE framework


class CUDEException(Exception):
    """
    A Custom CUDE Exception
    """
    pass
